# Generated by Django 5.0.7 on 2026-08-17 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('japanese_text', models.CharField(max_length=500, verbose_name='Yaponcha matn (savol/replika)')),
                ('romaji', models.CharField(blank=True, max_length=500, verbose_name='Romaji (talaffuz)')),
                ('translation', models.CharField(blank=True, max_length=500, verbose_name="Tarjima (o'zbekcha/inglizcha)")),
                ('answer_type', models.CharField(choices=[('choice', 'Variantlardan tanlash'), ('text', 'Matn kiritish (erkin javob)')], default='choice', max_length=10, verbose_name='Javob turi')),
                ('correct_answer_text', models.CharField(blank=True, help_text="Talaba matn kiritganda solishtirish uchun to'g'ri yaponcha javob.", max_length=500, verbose_name="To'g'ri javob matni (faqat 'matn kiritish' turi uchun)")),
                ('hint', models.CharField(blank=True, max_length=255, verbose_name='Maslahat (ixtiyoriy)')),
            ],
            options={
                'verbose_name': 'Dialog qadami',
                'verbose_name_plural': 'Dialog qadamlari',
                'ordering': ['scenario', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javobmi?")),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='trainer.conversationstep')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich (N5)"), ('intermediate', "O'rta (N4-N3)"), ('advanced', 'Yuqori (N2-N1)')], default='beginner', max_length=20, verbose_name='Daraja')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol (talabalarga ko'rinadi)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL, verbose_name="Yaratgan admin/o'qituvchi")),
            ],
            options={
                'verbose_name': 'Stsenariy',
                'verbose_name_plural': 'Stsenariylar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationstep',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='trainer.scenario', verbose_name='Stsenariy'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Urinish raqami')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan')], default='in_progress', max_length=15, verbose_name='Holat')),
                ('current_step_order', models.PositiveIntegerField(default=1, verbose_name='Joriy qadam')),
                ('total_steps', models.PositiveIntegerField(default=0, verbose_name='Jami qadamlar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('score', models.FloatField(default=0, verbose_name='Ball (%)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='trainer.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi jarayoni",
                'verbose_name_plural': "O'quvchi jarayonlari (Tarix)",
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStepAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer_text', models.CharField(max_length=500, verbose_name='Berilgan javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javobmi?")),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trainer.userprogress')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='trainer.conversationstep')),
            ],
            options={
                'verbose_name': 'Talaba javobi',
                'verbose_name_plural': 'Talaba javoblari',
                'ordering': ['step__order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='conversationstep',
            unique_together={('scenario', 'order')},
        ),
    ]
